FROM python:3.12-slim

WORKDIR /app
COPY gateway/pyproject.toml .
COPY gateway/poetry.lock .

RUN pip install poetry && \
    poetry config virtualenvs.create false && \
    poetry install --no-dev

COPY gateway .

CMD ["poetry", "run", "start"] 