FROM python:3.12-slim

WORKDIR /app
COPY web-crawl/pyproject.toml .
COPY web-crawl/poetry.lock .

RUN pip install poetry && \
    poetry config virtualenvs.create false && \
    poetry install --no-dev

COPY web-crawl .

CMD ["poetry", "run", "start"] 