FROM python:3.12-slim

WORKDIR /app
COPY whisper-core/pyproject.toml .
COPY whisper-core/poetry.lock .

RUN pip install poetry && \
    poetry config virtualenvs.create false && \
    poetry install --no-dev

COPY whisper-core .

CMD ["poetry", "run", "start"] 