FROM python:3.12-slim

WORKDIR /app
COPY deep-research/pyproject.toml .
COPY deep-research/poetry.lock .

RUN pip install poetry && \
    poetry config virtualenvs.create false && \
    poetry install --no-dev

COPY deep-research .

CMD ["poetry", "run", "start"] 